version: "3.9"

services:
  java-integration-test-intro-app:
    build:
      context: ../../../
      dockerfile: Dockerfile
    environment:
      DB_HOST: dbt.host
      DB_PORT: 5432
      DB_USERNAME: simplewebapp
      DB_PASSWORD: password1
      CATALOG_SERVICE_URL: http://external-catalog.host:8080
#      SPRING_PROFILES_ACTIVE: external
    ports:
      - "8080:8080"
    links:
      - "database:dbt.host"
      - "external-catalog:external-catalog.host"

  database:
    image: postgres:14.1
    environment:
      POSTGRES_USER: simplewebapp
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"

  external-catalog:
    image: wiremock/wiremock:2.35.0
    ports:
      - "8080"
    volumes:
      - ./wiremock:/home/wiremock
